SELECT ROUND(AVG(R1.LAT_N), 4) AS MEDIAN
FROM (SELECT @rownum := (@rownum + 1) AS 'ROW_NUM', S1.LAT_N
      FROM STATION AS S1, (SELECT @rownum := 0) AS R
      ORDER BY S1.LAT_N) AS R1, 
    (SELECT COUNT(*) AS TOTAL_ROWS
     FROM STATION AS S2) AS R2
WHERE R1.ROW_NUM IN (FLOOR((TOTAL_ROWS + 1) / 2), FLOOR((TOTAL_ROWS + 2) / 2));