SELECT CITY, LENGTH(CITY)
FROM (SELECT CITY
      FROM STATION
      ORDER BY LENGTH(CITY) ASC, CITY) 
WHERE ROWNUM = 1;

SELECT CITY, LENGTH(CITY)
FROM (SELECT CITY
      FROM STATION
      ORDER BY LENGTH(CITY) DESC, CITY) 
WHERE ROWNUM = 1;